//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 11:05:30 AM CEST 
//


package jaxb.from.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.from.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClanSadrzajTekst_QNAME = new QName("http://www.parlament.gov.rs/clan", "Tekst");
    private final static QName _ClanSadrzajStav_QNAME = new QName("http://www.parlament.gov.rs/clan", "Stav");
    private final static QName _ClanSadrzajTekstNekiTekst_QNAME = new QName("http://www.parlament.gov.rs/clan", "Neki_tekst");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.from.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Propis }
     * 
     */
    public Propis createPropis() {
        return new Propis();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj }
     * 
     */
    public Clan.Sadrzaj createClanSadrzaj() {
        return new Clan.Sadrzaj();
    }

    /**
     * Create an instance of {@link Propis.Deo }
     * 
     */
    public Propis.Deo createPropisDeo() {
        return new Propis.Deo();
    }

    /**
     * Create an instance of {@link Propis.Deo.Glava }
     * 
     */
    public Propis.Deo.Glava createPropisDeoGlava() {
        return new Propis.Deo.Glava();
    }

    /**
     * Create an instance of {@link Propis.Deo.Glava.Odeljak }
     * 
     */
    public Propis.Deo.Glava.Odeljak createPropisDeoGlavaOdeljak() {
        return new Propis.Deo.Glava.Odeljak();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Tekst }
     * 
     */
    public Clan.Sadrzaj.Tekst createClanSadrzajTekst() {
        return new Clan.Sadrzaj.Tekst();
    }

    /**
     * Create an instance of {@link Propis.Deo.Glava.Odeljak.Pododeljak }
     * 
     */
    public Propis.Deo.Glava.Odeljak.Pododeljak createPropisDeoGlavaOdeljakPododeljak() {
        return new Propis.Deo.Glava.Odeljak.Pododeljak();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Sadrzaj.Tekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/clan", name = "Tekst", scope = Clan.Sadrzaj.class)
    public JAXBElement<Clan.Sadrzaj.Tekst> createClanSadrzajTekst(Clan.Sadrzaj.Tekst value) {
        return new JAXBElement<Clan.Sadrzaj.Tekst>(_ClanSadrzajTekst_QNAME, Clan.Sadrzaj.Tekst.class, Clan.Sadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/clan", name = "Stav", scope = Clan.Sadrzaj.class)
    public JAXBElement<String> createClanSadrzajStav(String value) {
        return new JAXBElement<String>(_ClanSadrzajStav_QNAME, String.class, Clan.Sadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/clan", name = "Neki_tekst", scope = Clan.Sadrzaj.Tekst.class)
    public JAXBElement<String> createClanSadrzajTekstNekiTekst(String value) {
        return new JAXBElement<String>(_ClanSadrzajTekstNekiTekst_QNAME, String.class, Clan.Sadrzaj.Tekst.class, value);
    }

}
