//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:55:49 PM CEST 
//


package jaxb.from.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.from.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.from.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Propis }
     * 
     */
    public Propis createPropis() {
        return new Propis();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj }
     * 
     */
    public Clan.Sadrzaj createClanSadrzaj() {
        return new Clan.Sadrzaj();
    }

    /**
     * Create an instance of {@link Propis.Deo }
     * 
     */
    public Propis.Deo createPropisDeo() {
        return new Propis.Deo();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Stav }
     * 
     */
    public Clan.Sadrzaj.Stav createClanSadrzajStav() {
        return new Clan.Sadrzaj.Stav();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Tekst }
     * 
     */
    public Clan.Sadrzaj.Tekst createClanSadrzajTekst() {
        return new Clan.Sadrzaj.Tekst();
    }

    /**
     * Create an instance of {@link Propis.Deo.Glava }
     * 
     */
    public Propis.Deo.Glava createPropisDeoGlava() {
        return new Propis.Deo.Glava();
    }

}
