//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 11:40:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.parlament.gov.rs/propis", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
				xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "akt",  namespaceURI="http://www.parlament.gov.rs/akt"),
						 @javax.xml.bind.annotation.XmlNs(prefix = "aman", namespaceURI="http://www.parlament.gov.rs/amandman"),
						 @javax.xml.bind.annotation.XmlNs(prefix = "pro",  namespaceURI="http://www.parlament.gov.rs/propis"),
						 @javax.xml.bind.annotation.XmlNs(prefix = "clan", namespaceURI="http://www.parlament.gov.rs/clan"),
						 @javax.xml.bind.annotation.XmlNs(prefix = "pred", namespaceURI="http://www.parlament.gov.rs/predicate"),
						 @javax.xml.bind.annotation.XmlNs(prefix = "",     namespaceURI="http://www.w3.org/ns/rdfa#"),
	        			 @javax.xml.bind.annotation.XmlNs(prefix = "xs",   namespaceURI="http://www.w3.org/2001/XMLSchema")}
		)
package jaxb.from.xsd;
