//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 01:02:49 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://en.wikipedia.org/wiki/Role-based_access_control", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package web.xml.role;
